version: "3.9"

networks:
  net:
    name: proyecto-central-net

volumes:
  pgdata:

services:
  postgres:
    image: postgres:16-alpine
    container_name: pc-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: proyecto_central
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./scripts/init-dbs.sh:/docker-entrypoint-initdb.d/init-dbs.sh:ro
    networks:
      - net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d proyecto_central"]
      interval: 5s
      timeout: 3s
      retries: 5

  portfolio:
    build: ./portfolio
    container_name: pc-portfolio
    restart: unless-stopped
    ports:
      - "4000:4000"
    environment:
      PORT: 4000
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: admin
      DB_PASS: admin123
      DB_NAME: portfolio_db
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - net
