apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: ${GRAFANA_DB_HOST}:5432
    database: ${GRAFANA_DB_NAME}
    user: ${GRAFANA_DB_USER}
    secureJsonData:
      password: ${GRAFANA_DB_PASS}
    jsonData:
      sslmode: ${GRAFANA_DB_SSLMODE:disable}
      postgresVersion: 1600
      timescaledb: false
