apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: ${GRAFANA_DB_HOST}:${GRAFANA_DB_PORT}
    database: ${GRAFANA_DB_NAME}
    user: ${GRAFANA_DB_USER}
    secureJsonData:
      password: ${GRAFANA_DB_PASS}
    jsonData:
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
