apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    database: portfolio_db
    user: admin
    secureJsonData:
      password: admin123
    jsonData:
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
  - name: PostgreSQL (proyecto_central)
    type: postgres
    access: proxy
    url: postgres:5432
    database: proyecto_central
    user: admin
    secureJsonData:
      password: admin123
    jsonData:
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
